# Generated by Django 3.1.7 on 2021-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='0769094443', max_length=10),
            preserve_default=False,
        ),
    ]
